# Generated by Django 6.1 on 2026-08-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/', verbose_name='Изображение вакансии'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес на карте'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='job',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('manual', 'Ручное'), ('somon_tj', 'somon.tj')], default='manual', max_length=20, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='job',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID в источнике'),
        ),
        migrations.AddField(
            model_name='job',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на источник'),
        ),
    ]
