# Generated by Django 6.1 on 2026-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='github_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Портфолио'),
        ),
    ]
