# Generated by Django 6.1 on 2026-09-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_resume_github_url_resume_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='style',
            field=models.CharField(choices=[('classic', 'Классический'), ('modern', 'Современный'), ('minimal', 'Минималистичный'), ('creative', 'Креативный')], default='modern', max_length=20, verbose_name='Стиль резюме'),
        ),
    ]
